package com.aics;
// Generated 16/12/2023 00:26:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idcursos;
     private String curso;
     private Date inicio;
     private String HInicio;
     private String HFin;
     private Integer capacidad;
     private Date finalizacion;
     private String cursoscol;
     private Integer idProfesor;
     private Integer idAlumno;
     private Date createStamp;

    public Curso() {
    }

    public Curso(String curso, Date inicio, String HInicio, String HFin, Integer capacidad, Date finalizacion, String cursoscol, Integer idProfesor, Integer idAlumno, Date createStamp) {
       this.curso = curso;
       this.inicio = inicio;
       this.HInicio = HInicio;
       this.HFin = HFin;
       this.capacidad = capacidad;
       this.finalizacion = finalizacion;
       this.cursoscol = cursoscol;
       this.idProfesor = idProfesor;
       this.idAlumno = idAlumno;
       this.createStamp = createStamp;
    }
   
    public Integer getIdcursos() {
        return this.idcursos;
    }
    
    public void setIdcursos(Integer idcursos) {
        this.idcursos = idcursos;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public String getHInicio() {
        return this.HInicio;
    }
    
    public void setHInicio(String HInicio) {
        this.HInicio = HInicio;
    }
    public String getHFin() {
        return this.HFin;
    }
    
    public void setHFin(String HFin) {
        this.HFin = HFin;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public Date getFinalizacion() {
        return this.finalizacion;
    }
    
    public void setFinalizacion(Date finalizacion) {
        this.finalizacion = finalizacion;
    }
    public String getCursoscol() {
        return this.cursoscol;
    }
    
    public void setCursoscol(String cursoscol) {
        this.cursoscol = cursoscol;
    }
    public Integer getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }
    public Integer getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date createStamp) {
        this.createStamp = createStamp;
    }




}


