package com.aics;
// Generated 16/12/2023 00:26:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Inscripcion generated by hbm2java
 */
public class Inscripcion  implements java.io.Serializable {


     private Integer idinscripciones;
     private Integer idCursos;
     private Integer idAlumnos;
     private String inscripcionescol;
     private Date createStamp;

    public Inscripcion() {
    }

    public Inscripcion(Integer idCursos, Integer idAlumnos, String inscripcionescol, Date createStamp) {
       this.idCursos = idCursos;
       this.idAlumnos = idAlumnos;
       this.inscripcionescol = inscripcionescol;
       this.createStamp = createStamp;
    }
   
    public Integer getIdinscripciones() {
        return this.idinscripciones;
    }
    
    public void setIdinscripciones(Integer idinscripciones) {
        this.idinscripciones = idinscripciones;
    }
    public Integer getIdCursos() {
        return this.idCursos;
    }
    
    public void setIdCursos(Integer idCursos) {
        this.idCursos = idCursos;
    }
    public Integer getIdAlumnos() {
        return this.idAlumnos;
    }
    
    public void setIdAlumnos(Integer idAlumnos) {
        this.idAlumnos = idAlumnos;
    }
    public String getInscripcionescol() {
        return this.inscripcionescol;
    }
    
    public void setInscripcionescol(String inscripcionescol) {
        this.inscripcionescol = inscripcionescol;
    }
    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date createStamp) {
        this.createStamp = createStamp;
    }




}


