package com.aics;
// Generated 16/12/2023 00:26:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer idprofesor;
     private Integer dni;
     private String apellido;
     private String nombre;
     private Date fechaNac;
     private Byte estado;
     private String tel;
     private String email;
     private Date createStamp;

    public Profesor() {
    }

    public Profesor(Integer dni, String apellido, String nombre, Date fechaNac, Byte estado, String tel, String email, Date createStamp) {
       this.dni = dni;
       this.apellido = apellido;
       this.nombre = nombre;
       this.fechaNac = fechaNac;
       this.estado = estado;
       this.tel = tel;
       this.email = email;
       this.createStamp = createStamp;
    }
   
    public Integer getIdprofesor() {
        return this.idprofesor;
    }
    
    public void setIdprofesor(Integer idprofesor) {
        this.idprofesor = idprofesor;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(Byte estado) {
        this.estado = estado;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date createStamp) {
        this.createStamp = createStamp;
    }




}


