/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aics.vistas;

/**
 *
 * @author tonym
 */
public class Administration extends javax.swing.JPanel {

    /**
     * Creates new form Administration
     */
    public Administration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPCursos = new javax.swing.JPanel();
        jPAlumnos = new javax.swing.JPanel();
        jPInscripciones = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 153, 153));

        javax.swing.GroupLayout jPCursosLayout = new javax.swing.GroupLayout(jPCursos);
        jPCursos.setLayout(jPCursosLayout);
        jPCursosLayout.setHorizontalGroup(
            jPCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        jPCursosLayout.setVerticalGroup(
            jPCursosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Recibo", jPCursos);

        javax.swing.GroupLayout jPAlumnosLayout = new javax.swing.GroupLayout(jPAlumnos);
        jPAlumnos.setLayout(jPAlumnosLayout);
        jPAlumnosLayout.setHorizontalGroup(
            jPAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        jPAlumnosLayout.setVerticalGroup(
            jPAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bajas", jPAlumnos);

        javax.swing.GroupLayout jPInscripcionesLayout = new javax.swing.GroupLayout(jPInscripciones);
        jPInscripciones.setLayout(jPInscripcionesLayout);
        jPInscripcionesLayout.setHorizontalGroup(
            jPInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        jPInscripcionesLayout.setVerticalGroup(
            jPInscripcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Estado", jPInscripciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 734, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPAlumnos;
    private javax.swing.JPanel jPCursos;
    private javax.swing.JPanel jPInscripciones;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
