/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aics.vistas;

import CRUD.Conectar;
import com.aics.model.User;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author tonym
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        this.setLocationRelativeTo(this);
        String dir = "src/imgs/20220921_195645.jpg";
        SetImageLabel(jLimgctr,dir);
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginJpBgr = new javax.swing.JPanel();
        loginJpUp = new javax.swing.JPanel();
        jLimgUpRight = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginJpSd = new javax.swing.JPanel();
        jTextUsuario = new javax.swing.JTextField();
        jLabelUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelContra = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jTextPass = new javax.swing.JPasswordField();
        jPButtonEntrar = new javax.swing.JPanel();
        jLabelButtonEntrar = new javax.swing.JLabel();
        jLabelResult = new javax.swing.JLabel();
        loginJpctr = new javax.swing.JPanel();
        jLimgctr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1800, 1050));
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setName("loginframe"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1319, 811));

        loginJpBgr.setLayout(new java.awt.BorderLayout());

        loginJpUp.setBackground(new java.awt.Color(7, 131, 193));
        loginJpUp.setPreferredSize(new java.awt.Dimension(1289, 150));
        loginJpUp.setLayout(new java.awt.BorderLayout());

        jLimgUpRight.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        jLimgUpRight.setForeground(new java.awt.Color(255, 255, 255));
        jLimgUpRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/american_1.png"))); // NOI18N
        jLimgUpRight.setText("American Institute");
        jLimgUpRight.setMaximumSize(new java.awt.Dimension(250, 200));
        jLimgUpRight.setMinimumSize(new java.awt.Dimension(250, 200));
        jLimgUpRight.setPreferredSize(new java.awt.Dimension(250, 200));
        loginJpUp.add(jLimgUpRight, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("X");
        jLabel1.setToolTipText("Cerrar");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        loginJpUp.add(jLabel1, java.awt.BorderLayout.LINE_END);

        loginJpBgr.add(loginJpUp, java.awt.BorderLayout.PAGE_START);

        loginJpSd.setBackground(new java.awt.Color(19, 137, 196));
        loginJpSd.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        loginJpSd.setPreferredSize(new java.awt.Dimension(220, 600));

        jTextUsuario.setBackground(new java.awt.Color(19, 137, 196));
        jTextUsuario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 14)); // NOI18N
        jTextUsuario.setForeground(new java.awt.Color(204, 204, 204));
        jTextUsuario.setText("Ingrese un USUARIO");
        jTextUsuario.setBorder(null);
        jTextUsuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextUsuarioFocusGained(evt);
            }
        });
        jTextUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextUsuarioMousePressed(evt);
            }
        });
        jTextUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsuarioActionPerformed(evt);
            }
        });

        jLabelUsuario.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsuario.setText("Usuario:");

        jLabelContra.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabelContra.setForeground(new java.awt.Color(255, 255, 255));
        jLabelContra.setText("Contraseña:");

        jTextPass.setBackground(new java.awt.Color(19, 137, 196));
        jTextPass.setForeground(new java.awt.Color(204, 204, 204));
        jTextPass.setText("********");
        jTextPass.setBorder(null);
        jTextPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPassFocusGained(evt);
            }
        });
        jTextPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextPassMousePressed(evt);
            }
        });

        jPButtonEntrar.setBackground(new java.awt.Color(7, 131, 190));
        jPButtonEntrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jPButtonEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonEntrarMouseEntered(evt);
            }
        });

        jLabelButtonEntrar.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButtonEntrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonEntrar.setText("Entrar");
        jLabelButtonEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonEntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonEntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonEntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPButtonEntrarLayout = new javax.swing.GroupLayout(jPButtonEntrar);
        jPButtonEntrar.setLayout(jPButtonEntrarLayout);
        jPButtonEntrarLayout.setHorizontalGroup(
            jPButtonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPButtonEntrarLayout.setVerticalGroup(
            jPButtonEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jLabelResult.setForeground(new java.awt.Color(255, 255, 255));
        jLabelResult.setText("jLabel2");

        javax.swing.GroupLayout loginJpSdLayout = new javax.swing.GroupLayout(loginJpSd);
        loginJpSd.setLayout(loginJpSdLayout);
        loginJpSdLayout.setHorizontalGroup(
            loginJpSdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJpSdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginJpSdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jTextPass)
                    .addComponent(jPButtonEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(loginJpSdLayout.createSequentialGroup()
                        .addGroup(loginJpSdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUsuario)
                            .addComponent(jLabelContra)
                            .addComponent(jLabelResult))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        loginJpSdLayout.setVerticalGroup(
            loginJpSdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJpSdLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelContra)
                .addGap(11, 11, 11)
                .addComponent(jTextPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPButtonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelResult)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        loginJpBgr.add(loginJpSd, java.awt.BorderLayout.WEST);

        loginJpctr.setBackground(new java.awt.Color(255, 255, 255));

        jLimgctr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLimgctr.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLimgctr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout loginJpctrLayout = new javax.swing.GroupLayout(loginJpctr);
        loginJpctr.setLayout(loginJpctrLayout);
        loginJpctrLayout.setHorizontalGroup(
            loginJpctrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLimgctr, javax.swing.GroupLayout.DEFAULT_SIZE, 1099, Short.MAX_VALUE)
        );
        loginJpctrLayout.setVerticalGroup(
            loginJpctrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLimgctr, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
        );

        jLimgctr.getAccessibleContext().setAccessibleName("jLimgctr");

        loginJpBgr.add(loginJpctr, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginJpBgr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginJpBgr, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));            // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(WIDTH);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPButtonEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonEntrarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPButtonEntrarMouseEntered

    private void jLabelButtonEntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonEntrarMouseEntered
    jPButtonEntrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonEntrarMouseEntered

    private void jLabelButtonEntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonEntrarMouseExited
    jPButtonEntrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonEntrarMouseExited

    private void jPButtonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonEntrarMouseClicked
    
    
    }//GEN-LAST:event_jPButtonEntrarMouseClicked

    private void jLabelButtonEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonEntrarMouseClicked
    Conectar conectar = new Conectar();
    // usuario = new User();
    String passText = new String(jTextPass.getPassword());
    User usuario = conectar.logIn(jTextUsuario.getText(), passText);
    if (usuario == null){
        jLabelResult.setText("Usuario inexistente");
    }else{
        jLabelResult.setText("Usuario verificado con el ID: "+usuario.getIduser().toString());
        //Thread.sleep(1000);
        main principal = new main();
        principal.setVisible(true);
        dispose();
        
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonEntrarMouseClicked

    private void jTextUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextUsuarioMousePressed
        if (jTextUsuario.getText().equals("Ingrese un USUARIO")){
            jTextUsuario.setText("");
            jTextUsuario.setForeground(Color.WHITE);
        }
        if(String.valueOf(jTextPass.getPassword()).isEmpty()){
            jTextPass.setText("********");
            jTextPass.setForeground(new java.awt.Color(204, 204, 204)); 
        }
        
    }//GEN-LAST:event_jTextUsuarioMousePressed

    private void jTextPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPassMousePressed
        if(String.valueOf(jTextPass.getPassword()).equals("********")){
            jTextPass.setText("");
            jTextPass.setForeground(Color.WHITE);
        }
        if (jTextUsuario.getText().isEmpty()){
            jTextUsuario.setText("Ingrese un USUARIO");
            jTextUsuario.setForeground(new java.awt.Color(204, 204, 204));
        }
        
    }//GEN-LAST:event_jTextPassMousePressed

    private void jTextUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsuarioActionPerformed

    private void jTextUsuarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextUsuarioFocusGained
        if(String.valueOf(jTextPass.getPassword()).equals("********")){
            jTextPass.setText("");
            jTextPass.setForeground(Color.WHITE);
        }
        if (jTextUsuario.getText().isEmpty()){
            jTextUsuario.setText("Ingrese un USUARIO");
            jTextUsuario.setForeground(new java.awt.Color(204, 204, 204));
        }
    }//GEN-LAST:event_jTextUsuarioFocusGained

    private void jTextPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPassFocusGained
       if(String.valueOf(jTextPass.getPassword()).equals("********")){
            jTextPass.setText("");
            jTextPass.setForeground(Color.WHITE);
        }
        if (jTextUsuario.getText().isEmpty()){
            jTextUsuario.setText("Ingrese un USUARIO");
            jTextUsuario.setForeground(new java.awt.Color(204, 204, 204));
        } 
    }//GEN-LAST:event_jTextPassFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    private void SetImageLabel(JLabel labelN, String dir){
       ImageIcon fondo1 = new ImageIcon(dir);
       Icon fondoImg1 = new ImageIcon(fondo1.getImage().getScaledInstance(labelN.getWidth(), labelN.getHeight(), Image.SCALE_DEFAULT)
       );
       labelN.setIcon(fondoImg1);
       this.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelButtonEntrar;
    private javax.swing.JLabel jLabelContra;
    private javax.swing.JLabel jLabelResult;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLimgUpRight;
    private javax.swing.JLabel jLimgctr;
    private javax.swing.JPanel jPButtonEntrar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField jTextPass;
    private javax.swing.JTextField jTextUsuario;
    private javax.swing.JPanel loginJpBgr;
    private javax.swing.JPanel loginJpSd;
    private javax.swing.JPanel loginJpUp;
    private javax.swing.JPanel loginJpctr;
    // End of variables declaration//GEN-END:variables
}
