/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aics.vistas;

import CRUD.Conectar;
import com.aics.model.User;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.HashSet;
import java.util.Set;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author tonym
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public main() {
        initComponents();
        this.setLocationRelativeTo(this);
        String dir = "src/imgs/fondo.png";
        SetImageLabel(jLimgctr,dir);
         
        
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainJpBgr = new javax.swing.JPanel();
        mainJpUp = new javax.swing.JPanel();
        jLimgUpRight = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        mainJpSd = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPButtonAcademy = new javax.swing.JPanel();
        jLabelButtonAcademy = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPButtonAdministration = new javax.swing.JPanel();
        jLabelButtonAdministration = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jPButtonReports = new javax.swing.JPanel();
        jLabelButtonReports = new javax.swing.JLabel();
        loginJpctr = new javax.swing.JPanel();
        jLimgctr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.TOOLKIT_EXCLUDE);
        setName("loginframe"); // NOI18N
        setUndecorated(true);

        mainJpBgr.setLayout(new java.awt.BorderLayout());

        mainJpUp.setBackground(new java.awt.Color(7, 131, 193));
        mainJpUp.setPreferredSize(new java.awt.Dimension(1289, 150));
        mainJpUp.setLayout(new java.awt.BorderLayout());

        jLimgUpRight.setFont(new java.awt.Font("Old English Text MT", 0, 24)); // NOI18N
        jLimgUpRight.setForeground(new java.awt.Color(255, 255, 255));
        jLimgUpRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/american_1.png"))); // NOI18N
        jLimgUpRight.setText("American Institute");
        jLimgUpRight.setMaximumSize(new java.awt.Dimension(250, 200));
        jLimgUpRight.setMinimumSize(new java.awt.Dimension(250, 200));
        jLimgUpRight.setPreferredSize(new java.awt.Dimension(250, 200));
        mainJpUp.add(jLimgUpRight, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("X");
        jLabel1.setToolTipText("Cerrar");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        mainJpUp.add(jLabel1, java.awt.BorderLayout.LINE_END);

        mainJpBgr.add(mainJpUp, java.awt.BorderLayout.PAGE_START);

        mainJpSd.setBackground(new java.awt.Color(19, 137, 196));
        mainJpSd.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        mainJpSd.setPreferredSize(new java.awt.Dimension(220, 600));

        jPButtonAcademy.setBackground(new java.awt.Color(7, 131, 190));
        jPButtonAcademy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPButtonAcademy.setForeground(new java.awt.Color(255, 255, 255));
        jPButtonAcademy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonAcademy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonAcademyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonAcademyMouseEntered(evt);
            }
        });

        jLabelButtonAcademy.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelButtonAcademy.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButtonAcademy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonAcademy.setText("Académica");
        jLabelButtonAcademy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonAcademyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonAcademyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonAcademyMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPButtonAcademyLayout = new javax.swing.GroupLayout(jPButtonAcademy);
        jPButtonAcademy.setLayout(jPButtonAcademyLayout);
        jPButtonAcademyLayout.setHorizontalGroup(
            jPButtonAcademyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonAcademy, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        jPButtonAcademyLayout.setVerticalGroup(
            jPButtonAcademyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonAcademy, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPButtonAdministration.setBackground(new java.awt.Color(7, 131, 190));
        jPButtonAdministration.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPButtonAdministration.setForeground(new java.awt.Color(255, 255, 255));
        jPButtonAdministration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonAdministration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonAdministrationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonAdministrationMouseEntered(evt);
            }
        });

        jLabelButtonAdministration.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelButtonAdministration.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButtonAdministration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonAdministration.setText("Administración");
        jLabelButtonAdministration.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonAdministrationMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonAdministrationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonAdministrationMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPButtonAdministrationLayout = new javax.swing.GroupLayout(jPButtonAdministration);
        jPButtonAdministration.setLayout(jPButtonAdministrationLayout);
        jPButtonAdministrationLayout.setHorizontalGroup(
            jPButtonAdministrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonAdministration, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        jPButtonAdministrationLayout.setVerticalGroup(
            jPButtonAdministrationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonAdministration, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        jPButtonReports.setBackground(new java.awt.Color(7, 131, 190));
        jPButtonReports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPButtonReports.setForeground(new java.awt.Color(255, 255, 255));
        jPButtonReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPButtonReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPButtonReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPButtonReportsMouseEntered(evt);
            }
        });

        jLabelButtonReports.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabelButtonReports.setForeground(new java.awt.Color(255, 255, 255));
        jLabelButtonReports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelButtonReports.setText("Reportes");
        jLabelButtonReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelButtonReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelButtonReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelButtonReportsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPButtonReportsLayout = new javax.swing.GroupLayout(jPButtonReports);
        jPButtonReports.setLayout(jPButtonReportsLayout);
        jPButtonReportsLayout.setHorizontalGroup(
            jPButtonReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonReports, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );
        jPButtonReportsLayout.setVerticalGroup(
            jPButtonReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelButtonReports, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainJpSdLayout = new javax.swing.GroupLayout(mainJpSd);
        mainJpSd.setLayout(mainJpSdLayout);
        mainJpSdLayout.setHorizontalGroup(
            mainJpSdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJpSdLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainJpSdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jPButtonAcademy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJpSdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPButtonReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(mainJpSdLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainJpSdLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPButtonAdministration, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(mainJpSdLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        mainJpSdLayout.setVerticalGroup(
            mainJpSdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainJpSdLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPButtonAcademy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPButtonAdministration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPButtonReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(343, Short.MAX_VALUE))
        );

        mainJpBgr.add(mainJpSd, java.awt.BorderLayout.WEST);

        loginJpctr.setBackground(new java.awt.Color(255, 255, 255));
        loginJpctr.setPreferredSize(new java.awt.Dimension(1084, 561));

        jLimgctr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLimgctr.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLimgctr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout loginJpctrLayout = new javax.swing.GroupLayout(loginJpctr);
        loginJpctr.setLayout(loginJpctrLayout);
        loginJpctrLayout.setHorizontalGroup(
            loginJpctrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginJpctrLayout.createSequentialGroup()
                .addGap(1094, 1094, 1094)
                .addComponent(jLimgctr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginJpctrLayout.setVerticalGroup(
            loginJpctrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLimgctr, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
        );

        jLimgctr.getAccessibleContext().setAccessibleName("jLimgctr");

        mainJpBgr.add(loginJpctr, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJpBgr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainJpBgr, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
   // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1FocusGained

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));            // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        System.exit(WIDTH);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jPButtonAcademyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonAcademyMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPButtonAcademyMouseEntered

    private void jLabelButtonAcademyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonAcademyMouseEntered
    jPButtonAcademy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonAcademyMouseEntered

    private void jLabelButtonAcademyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonAcademyMouseExited
    jPButtonAcademy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonAcademyMouseExited

    private void jPButtonAcademyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonAcademyMouseClicked
    
        
    
    }//GEN-LAST:event_jPButtonAcademyMouseClicked

    private void jLabelButtonAcademyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonAcademyMouseClicked
    jPButtonAcademy.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
    jPButtonAcademy.setBackground(new java.awt.Color(47, 89, 94)); //[7,131,190]
    jPButtonAdministration.setBackground(new java.awt.Color(7, 131, 190)); //[7,131,190]
    jPButtonReports.setBackground(new java.awt.Color(7, 131, 190)); //[7,131,190]
    Academics jpanelAcademics = new Academics();
    ShowjPanel(jpanelAcademics,loginJpctr);
    
    
    }//GEN-LAST:event_jLabelButtonAcademyMouseClicked

    private void jLabelButtonAdministrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonAdministrationMouseClicked
    jPButtonAdministration.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
    jPButtonAdministration.setBackground(new java.awt.Color(47, 89, 94)); //[7,131,190]
    jPButtonAcademy.setBackground(new java.awt.Color(7, 131, 190)); //[7,131,190]
    jPButtonReports.setBackground(new java.awt.Color(7, 131, 190)); //[7,131,190]
    Administration jpanelAdmin = new Administration();
    ShowjPanel(jpanelAdmin,loginJpctr);
    }//GEN-LAST:event_jLabelButtonAdministrationMouseClicked

    private void jLabelButtonAdministrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonAdministrationMouseEntered
    jPButtonAdministration.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonAdministrationMouseEntered

    private void jLabelButtonAdministrationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonAdministrationMouseExited
    jPButtonAdministration.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));    // TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonAdministrationMouseExited

    private void jPButtonAdministrationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonAdministrationMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPButtonAdministrationMouseClicked

    private void jPButtonAdministrationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonAdministrationMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPButtonAdministrationMouseEntered

    private void jLabelButtonReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonReportsMouseClicked
    jPButtonReports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true));
    jPButtonReports.setBackground(new java.awt.Color(47, 89, 94)); //[7,131,190]
    jPButtonAdministration.setBackground(new java.awt.Color(7, 131, 190)); //[7,131,190]
    jPButtonAcademy.setBackground(new java.awt.Color(7, 131, 190)); //[7,131,190]
    Reports jpanelRepo = new Reports();
    ShowjPanel(jpanelRepo,loginJpctr);    
    }//GEN-LAST:event_jLabelButtonReportsMouseClicked

    private void jLabelButtonReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonReportsMouseEntered
    jPButtonReports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));    // TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonReportsMouseEntered

    private void jLabelButtonReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelButtonReportsMouseExited
    jPButtonReports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));    // TODO add your handling code here:
    }//GEN-LAST:event_jLabelButtonReportsMouseExited

    private void jPButtonReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonReportsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPButtonReportsMouseClicked

    private void jPButtonReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPButtonReportsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPButtonReportsMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
       
        
        
        
    }

    private void SetImageLabel(JLabel labelN, String dir){
       ImageIcon fondo1 = new ImageIcon(dir);
       Icon fondoImg1 = new ImageIcon(fondo1.getImage().getScaledInstance(labelN.getWidth(), labelN.getHeight(), Image.SCALE_DEFAULT)
       );
       labelN.setIcon(fondoImg1);
       this.repaint();
    }
    
    private void ShowjPanel(JPanel jp,JPanel jpbgr){
        //Academics jpanelAcademics = new Academics();
        jp.setSize(1084, 561);
        jp.setLocation(0, 0);
        jpbgr.removeAll();
        jpbgr.add(jp, BorderLayout.CENTER);
        jpbgr.revalidate();
        jpbgr.repaint();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelButtonAcademy;
    private javax.swing.JLabel jLabelButtonAdministration;
    private javax.swing.JLabel jLabelButtonReports;
    private javax.swing.JLabel jLimgUpRight;
    private javax.swing.JLabel jLimgctr;
    private javax.swing.JPanel jPButtonAcademy;
    private javax.swing.JPanel jPButtonAdministration;
    private javax.swing.JPanel jPButtonReports;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel loginJpctr;
    private javax.swing.JPanel mainJpBgr;
    private javax.swing.JPanel mainJpSd;
    private javax.swing.JPanel mainJpUp;
    // End of variables declaration//GEN-END:variables
}
