package model;
// Generated 03/06/2025 21:07:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer idAlumno;
     private Integer dni;
     private String apellido;
     private String nombre;
     private Date fechaNac;
     private Byte estado;
     private String tel;
     private String email;
     private Date createStamp;
     private Set inscripcions = new HashSet(0);

    public Alumno() {
    }

    public Alumno(Integer dni, String apellido, String nombre, Date fechaNac, Byte estado, String tel, String email, Date createStamp, Set inscripcions) {
       this.dni = dni;
       this.apellido = apellido;
       this.nombre = nombre;
       this.fechaNac = fechaNac;
       this.estado = estado;
       this.tel = tel;
       this.email = email;
       this.createStamp = createStamp;
       this.inscripcions = inscripcions;
    }
   
    public Integer getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Integer getDni() {
        return this.dni;
    }
    
    public void setDni(Integer dni) {
        this.dni = dni;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Byte getEstado() {
        return this.estado;
    }
    
    public void setEstado(Byte estado) {
        this.estado = estado;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date createStamp) {
        this.createStamp = createStamp;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }




}


