package model;
// Generated 03/06/2025 21:07:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia  implements java.io.Serializable {


     private Integer idasistencia;
     private Inscripcion inscripcion;
     private Date fecha;
     private Date horario;
     private String marca;
     private String asistenciacol;
     private Date createStamp;

    public Asistencia() {
    }

    public Asistencia(Inscripcion inscripcion, Date fecha, Date horario, String marca, String asistenciacol, Date createStamp) {
       this.inscripcion = inscripcion;
       this.fecha = fecha;
       this.horario = horario;
       this.marca = marca;
       this.asistenciacol = asistenciacol;
       this.createStamp = createStamp;
    }
   
    public Integer getIdasistencia() {
        return this.idasistencia;
    }
    
    public void setIdasistencia(Integer idasistencia) {
        this.idasistencia = idasistencia;
    }
    public Inscripcion getInscripcion() {
        return this.inscripcion;
    }
    
    public void setInscripcion(Inscripcion inscripcion) {
        this.inscripcion = inscripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHorario() {
        return this.horario;
    }
    
    public void setHorario(Date horario) {
        this.horario = horario;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getAsistenciacol() {
        return this.asistenciacol;
    }
    
    public void setAsistenciacol(String asistenciacol) {
        this.asistenciacol = asistenciacol;
    }
    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date createStamp) {
        this.createStamp = createStamp;
    }




}


