package model;
// Generated 03/06/2025 21:07:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CursoHorario generated by hbm2java
 */
public class CursoHorario  implements java.io.Serializable {


     private Integer id;
     private Curso curso;
     private String dia;
     private Date horaInicio;
     private Date horaFin;

    public CursoHorario() {
    }

    public CursoHorario(Curso curso, String dia, Date horaInicio, Date horaFin) {
       this.curso = curso;
       this.dia = dia;
       this.horaInicio = horaInicio;
       this.horaFin = horaFin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getDia() {
        return this.dia;
    }
    
    public void setDia(String dia) {
        this.dia = dia;
    }
    public Date getHoraInicio() {
        return this.horaInicio;
    }
    
    public void setHoraInicio(Date horaInicio) {
        this.horaInicio = horaInicio;
    }
    public Date getHoraFin() {
        return this.horaFin;
    }
    
    public void setHoraFin(Date horaFin) {
        this.horaFin = horaFin;
    }




}


