package model;
// Generated 03/06/2025 21:07:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idcursos;
     private Profesor profesor;
     private String curso;
     private Date inicio;
     private Integer capacidad;
     private Date finalizacion;
     private String estadoCurso;
     private Date createStamp;
     private Date modStamp;
     private Set cursoHorarios = new HashSet(0);
     private Set inscripcions = new HashSet(0);

    public Curso() {
    }

    public Curso(Profesor profesor, String curso, Date inicio, Integer capacidad, Date finalizacion, String estadoCurso, Date createStamp, Date modStamp, Set cursoHorarios, Set inscripcions) {
       this.profesor = profesor;
       this.curso = curso;
       this.inicio = inicio;
       this.capacidad = capacidad;
       this.finalizacion = finalizacion;
       this.estadoCurso = estadoCurso;
       this.createStamp = createStamp;
       this.modStamp = modStamp;
       this.cursoHorarios = cursoHorarios;
       this.inscripcions = inscripcions;
    }
   
    public Integer getIdcursos() {
        return this.idcursos;
    }
    
    public void setIdcursos(Integer idcursos) {
        this.idcursos = idcursos;
    }
    public Profesor getProfesor() {
        return this.profesor;
    }
    
    public void setProfesor(Profesor profesor) {
        this.profesor = profesor;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public Date getFinalizacion() {
        return this.finalizacion;
    }
    
    public void setFinalizacion(Date finalizacion) {
        this.finalizacion = finalizacion;
    }
    public String getEstadoCurso() {
        return this.estadoCurso;
    }
    
    public void setEstadoCurso(String estadoCurso) {
        this.estadoCurso = estadoCurso;
    }
    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date createStamp) {
        this.createStamp = createStamp;
    }
    public Date getModStamp() {
        return this.modStamp;
    }
    
    public void setModStamp(Date modStamp) {
        this.modStamp = modStamp;
    }
    public Set getCursoHorarios() {
        return this.cursoHorarios;
    }
    
    public void setCursoHorarios(Set cursoHorarios) {
        this.cursoHorarios = cursoHorarios;
    }
    public Set getInscripcions() {
        return this.inscripcions;
    }
    
    public void setInscripcions(Set inscripcions) {
        this.inscripcions = inscripcions;
    }




}


