package model;
// Generated 03/06/2025 21:07:18 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inscripcion generated by hbm2java
 */
public class Inscripcion  implements java.io.Serializable {


     private Integer idinscripciones;
     private Alumno alumno;
     private Curso curso;
     private Boolean estado;
     private Date createStamp;
     private Date modTimestamp;
     private Set asistencias = new HashSet(0);

    public Inscripcion() {
    }

    public Inscripcion(Alumno alumno, Curso curso, Boolean estado, Date createStamp, Date modTimestamp, Set asistencias) {
       this.alumno = alumno;
       this.curso = curso;
       this.estado = estado;
       this.createStamp = createStamp;
       this.modTimestamp = modTimestamp;
       this.asistencias = asistencias;
    }
   
    public Integer getIdinscripciones() {
        return this.idinscripciones;
    }
    
    public void setIdinscripciones(Integer idinscripciones) {
        this.idinscripciones = idinscripciones;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date createStamp) {
        this.createStamp = createStamp;
    }
    public Date getModTimestamp() {
        return this.modTimestamp;
    }
    
    public void setModTimestamp(Date modTimestamp) {
        this.modTimestamp = modTimestamp;
    }
    public Set getAsistencias() {
        return this.asistencias;
    }
    
    public void setAsistencias(Set asistencias) {
        this.asistencias = asistencias;
    }




}


