package com.aics.model;
// Generated 16/12/2023 00:26:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Asistencia generated by hbm2java
 */
public class Asistencia  implements java.io.Serializable {


     private Integer idasistencia;
     private Integer idAlumno;
     private Integer idCurso;
     private Date fecha;
     private Date horario;
     private String marca;
     private String asistenciacol;
     private Date createStamp;

    public Asistencia() {
    }

    public Asistencia(Integer idAlumno, Integer idCurso, Date fecha, Date horario, String marca, String asistenciacol, Date createStamp) {
       this.idAlumno = idAlumno;
       this.idCurso = idCurso;
       this.fecha = fecha;
       this.horario = horario;
       this.marca = marca;
       this.asistenciacol = asistenciacol;
       this.createStamp = createStamp;
    }
   
    public Integer getIdasistencia() {
        return this.idasistencia;
    }
    
    public void setIdasistencia(Integer idasistencia) {
        this.idasistencia = idasistencia;
    }
    public Integer getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHorario() {
        return this.horario;
    }
    
    public void setHorario(Date horario) {
        this.horario = horario;
    }
    public String getMarca() {
        return this.marca;
    }
    
    public void setMarca(String marca) {
        this.marca = marca;
    }
    public String getAsistenciacol() {
        return this.asistenciacol;
    }
    
    public void setAsistenciacol(String asistenciacol) {
        this.asistenciacol = asistenciacol;
    }
    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date createStamp) {
        this.createStamp = createStamp;
    }




}


