package com.aics.model;
// Generated 16/12/2023 00:26:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Recibo generated by hbm2java
 */
public class Recibo  implements java.io.Serializable {


     private Integer idRecibo;
     private Integer idAlumno;
     private Integer idCurso;
     private Long numRecibo;
     private Long monto;
     private Date createStamp;

    public Recibo() {
    }

    public Recibo(Integer idAlumno, Integer idCurso, Long numRecibo, Long monto, Date createStamp) {
       this.idAlumno = idAlumno;
       this.idCurso = idCurso;
       this.numRecibo = numRecibo;
       this.monto = monto;
       this.createStamp = createStamp;
    }
   
    public Integer getIdRecibo() {
        return this.idRecibo;
    }
    
    public void setIdRecibo(Integer idRecibo) {
        this.idRecibo = idRecibo;
    }
    public Integer getIdAlumno() {
        return this.idAlumno;
    }
    
    public void setIdAlumno(Integer idAlumno) {
        this.idAlumno = idAlumno;
    }
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }
    public Long getNumRecibo() {
        return this.numRecibo;
    }
    
    public void setNumRecibo(Long numRecibo) {
        this.numRecibo = numRecibo;
    }
    public Long getMonto() {
        return this.monto;
    }
    
    public void setMonto(Long monto) {
        this.monto = monto;
    }
    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date createStamp) {
        this.createStamp = createStamp;
    }




}


