package com.aics.model;
// Generated 16/12/2023 00:26:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idcursos;
     private String curso;
     private Date inicio;
//     private String HInicio;
//     private String HFin;
     private Integer capacidad;
     private Date finalizacion;
     private String estado_curso;
     private Integer idProfesor;     
//     private Integer idAlumno;
     private Date createStamp;
     private Date modStamp;

    public Curso() {
    }

    public Curso(String curso, Date inicio, Integer capacidad, Date finalizacion, String estado_curso, Integer idProfesor, Date create_stamp, Date mod_stamp) {
       this.curso = curso;
       this.inicio = inicio;
       //this.HInicio = HInicio;
       //this.HFin = HFin;
       this.capacidad = capacidad;
       this.finalizacion = finalizacion;
       this.estado_curso = estado_curso;
       this.idProfesor = idProfesor;
       //this.idAlumno = idAlumno;
       this.createStamp = create_stamp;
       this.modStamp = mod_stamp;
    }
   
    public Integer getIdcursos() {
        return this.idcursos;
    }
    
    public void setIdcursos(Integer idcursos) {
        this.idcursos = idcursos;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }
            
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public Date getFinalizacion() {
        return this.finalizacion;
    }
    
    public void setFinalizacion(Date finalizacion) {
        this.finalizacion = finalizacion;
    }
    public String getEstado_curso() {
        return this.estado_curso;
    }
    
    public void setEstado_curso(String estado_curso) {
        this.estado_curso = estado_curso;
    }
    public Integer getIdProfesor() {
        return this.idProfesor;
    }
    
    public void setIdProfesor(Integer idProfesor) {
        this.idProfesor = idProfesor;
    }

    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date create_stamp) {
        this.createStamp = create_stamp;
    }

    public Date getModStamp() {
        return this.modStamp;
    }
    
    public void setModStamp(Date mod_stamp) {
        this.modStamp = mod_stamp;
    }



}


