package com.aics.model;
// Generated 16/12/2023 00:26:11 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pagos generated by hbm2java
 */
public class Pagos  implements java.io.Serializable {


     private Integer idpagos;
     private Integer idprofesor;
     private Float horas;
     private Float precio;
     private Float total;
     private Date fecha;
     private String mes;
     private Date createStamp;

    public Pagos() {
    }

    public Pagos(Integer idprofesor, Float horas, Float precio, Float total, Date fecha, String mes, Date createStamp) {
       this.idprofesor = idprofesor;
       this.horas = horas;
       this.precio = precio;
       this.total = total;
       this.fecha = fecha;
       this.mes = mes;
       this.createStamp = createStamp;
    }
   
    public Integer getIdpagos() {
        return this.idpagos;
    }
    
    public void setIdpagos(Integer idpagos) {
        this.idpagos = idpagos;
    }
    public Integer getIdprofesor() {
        return this.idprofesor;
    }
    
    public void setIdprofesor(Integer idprofesor) {
        this.idprofesor = idprofesor;
    }
    public Float getHoras() {
        return this.horas;
    }
    
    public void setHoras(Float horas) {
        this.horas = horas;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Float getTotal() {
        return this.total;
    }
    
    public void setTotal(Float total) {
        this.total = total;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getMes() {
        return this.mes;
    }
    
    public void setMes(String mes) {
        this.mes = mes;
    }
    public Date getCreateStamp() {
        return this.createStamp;
    }
    
    public void setCreateStamp(Date createStamp) {
        this.createStamp = createStamp;
    }




}


